# Generated by Django 2.2.16 on 2022-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20221031_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Добавить картинку',
                null=True,
                upload_to='posts/',
                verbose_name='Картинка',
            ),
        ),
    ]
